name: Keep Render Awake

on:
  schedule:
    - cron: "*/5 * * * *"  # cada 5 minutos
  workflow_dispatch:       # permite ejecutarlo manualmente

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: curl https://TU-URL-ONRENDER.onrender.com/ping
